# AUTOGENERATED! DO NOT EDIT! File to edit: ../../pts/api/const.pct.py.

# %% auto 0
__all__ = ['scripts_path', 'assets_path']

# %% ../../pts/api/const.pct.py 3
from pathlib import Path
import toml
from typing import Optional
from pydantic import BaseModel, ConfigDict, model_validator
from pathlib import Path
from importlib import resources
import adulib, adulib.llm
from dotenv import load_dotenv
import magpy as proj

# %% ../../pts/api/const.pct.py 5
scripts_path = resources.files(f'{proj.__name__}').joinpath('scripts').resolve()
assets_path = resources.files(f'{proj.__name__}').joinpath('assets').resolve()
