# AUTOGENERATED! DO NOT EDIT! File to edit: ../../pts/api/utils.pct.py.

# %% auto 0
__all__ = ['foo']

# %% ../../pts/api/utils.pct.py 3
import magpy as proj
from . import const

# %% ../../pts/api/utils.pct.py 6
def foo():
    print("Hello")
